Change to basic

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -28,9 +28,10 @@ jobs:
         run: |
           for i in {1..5}; do
             echo "Attempt $i to deploy application..."
-            ssh -v -i ~/.ssh/ghactions ${{ secrets.DEPLOY_USER }}@${{ secrets.HOST }}
+            ssh -v -i ~/.ssh/ghactions ${{ secrets.DEPLOY_USER }}@${{ secrets.HOST }} << EOF
             set -e
-            mkdir -p ${{ secrets.DEPLOY_PATH }}
+            sudo mkdir -p ${{ secrets.DEPLOY_PATH }}
+            sudo chown ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_USER }} ${{ secrets.DEPLOY_PATH }}
             cd ${{ secrets.DEPLOY_PATH }}
             
             if [ ! -d ".git" ]; then
@@ -53,14 +54,12 @@ jobs:
             DB_NAME=${{ secrets.DB_NAME }} \
             docker compose up -d --build
             EOF
-          
-              if [ $? -eq 0 ]; then
-                echo "Deployment successful. Exiting loop."
-                break
-              fi
+            
+            if [ $? -eq 0 ]; then
+              echo "Deployment successful. Exiting loop."
+              break
+            fi
 
-              echo "Deployment failed. Retrying in 60 seconds..."
-              sleep 60
-            done
-  
-  
+            echo "Deployment failed. Retrying in 60 seconds..."
+            sleep 60
+          done
